# (Trimmed snippet — use the full code run above for direct copy)

from typing import List


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
import seaborn as sns
import inspect

from backtest.data_models import Trade, TradingState
from backtest.strategy import Strategy, FunctionStrategy

sns.set_style("whitegrid")

class Backtester:
    """
    
    The core Backtesting Engine. 
    
    Parameters
    ----------
    tradable_assets : List[str]
        The assets that the strategy will make trades on. 
        
    strategy_fn : Strategy
        The function that holds the core logic of the strategy. Must be wrapped into a Strategy object before it works. 
    
    data : pd.DataFrame
        The dataset that the strategy reads to make predictions. Can include more than price data from tradable_assets. 
        The dataset inputted will have the following restrictions:
        1. The columns that consists of the price that the strategy trades on MUST be named the ticker of the asset. E.g. if trading on Adj_Close price of NVDA, change Adj_Close column name to NVDA
        2. The index of the dataset must be in the form of a datetime index. 

    allow_short : bool, optional
        Straightforward.
        
    cash_start : float, optional
        The amount of capital that the strategy starts with. 
        
    commission : float, optional
        The commission obtained by the "broker" when trades are made. (default=0.0)
        
    slippage : float, optional
        
        
    execute_on_next_tick : bool, optional
        If True, portfolio is submitted
        
    periods_per_year : int, optional
        Will be depreciated soon. 
    
    riskfree_per_period : float, optional
        Will be depreciated soon. 
    
        
    Attributes
    ----------
    tradable_assets : List[str]
        The assets that the strategy will make trades on. 

    data : pd.DataFrame
        The dataset that the strategy reads to make predictions. 

    dates : pd.DatetimeIndex
        The date index of the dataset.
    
    cash_start : float
        The cash at the start of the 
        
    current_nav : float
        
    position : pd.Series
        
    current_shares : pd.Series
        
    cash : float
        
    commission : float
        
    slippage : float
        
    allow_short : bool
        Straightforward.

    execute_on_next_tick : bool
        If True, a requested portfolio is only executed on the prices of the next tick in the dataset.
    
    periods_per_year : int
        Staged for depreciation. 

    riskfree : float
        Staged for depreciation
        
    nav_history : pd.Series
        The history of Net Asset Value of the dataset. 
    
    position_history : pd.DataFrame
        The history of weights in each asset during the history of the backtest. 
        
    cash_history : pd.Series
        The amount of cash held by the strategy throughout the history of the backtest. 
        
    trades : List[Trade]
        The list of all trades sent to the 
        
    signal_history : List[float]
        The list of all signals generated by the strategy. 
        
    strategy_object : Strategy
        The core strategy object that is tested in the engine. 
        
    strategy_name : str
        The name of the strategy that can be used in plots later. 
        
    backtest_complete : bool
        
    portfolio_returns : pd.Series
        The returns series of the strategy. 
        
    """
    def __init__(self,
                tradable_assets: List[str], 
                strategy_fn: Strategy, # The strategy function I want to test on 
                strategy_name: str, # The name of the strategy for plotting
                data: pd.DataFrame, # the data that the strategy operates on
                allow_short=True,
                cash_start: float = 100_000.0,
                commission: float = 0.0,  
                slippage: float = 0.0, 
                execute_on_next_tick: bool = True,
                periods_per_year: int = 252,  # used for annualization
                riskfree_per_period: float = 0.0  # per-period risk-free rate (e.g., daily)   
                ):
        
        

        assert isinstance(data, pd.DataFrame), "Input data must be given as a pd.DataFrame indexed by date."
        assert isinstance(data.index, pd.DatetimeIndex), "Input data index must be a pd.DatetimeIndex."
        

        # Check the data that we need for signal generation
        self.tradable_assets = tradable_assets 
        self.data = data

        ## need to force that the data index is in the form of dates
        self.dates = data.index
        self.current_date = self.dates[0]
        
        # Current portfolio state
        self.cash_start = cash_start
        self.current_nav = cash_start
        self.position : pd.Series = pd.Series({asset:0 for asset in self.tradable_assets})
        self.current_shares: pd.Series = pd.Series({asset:0 for asset in self.tradable_assets})
        self.cash = cash_start

        # execution and model parameters
        self.commission = commission
        self.slippage = slippage
        self.allow_short = allow_short
        self.execute_on_next_tick = execute_on_next_tick
        self.periods_per_year = periods_per_year
        self.riskfree = riskfree_per_period

        # history
        self.nav_history: pd.Series = pd.Series(np.zeros(len(self.data)), index=self.dates)
        self.shares_history: pd.DataFrame = pd.DataFrame(np.zeros((len(self.data), len(self.tradable_assets))),  columns= self.tradable_assets, index= self.dates)    
        self.cash_history: pd.Series = pd.Series(np.zeros(len(self.data)), index=self.dates)
        # fraction of NAV invested in asset (dollars_in_asset / nav)
        self.trades: List[Trade] = []
        self.signal_history: List = []     # raw signals returned by strategy

        # Strategy 
        self.strategy_object = strategy_fn
        self.strategy_name = strategy_name

        # For plotting later 
        self.backtest_complete = False

        # For visualising results
        self.portfolio_returns = None


    # Debugging Functions 
    def _current_state(self):
        # Return a snapshot of current portfolio state (useful for debugging).
        current_prices = self.data.loc[self.current_date, self.tradable_assets]
        return {
            "cash": self.cash,
            # To dict method converts pandas Series to dictionary for easier view 
            "shares": self.position,
            "nav": self.cash + (self.position * current_prices).sum()
        }

    def _build_trading_state(self, date: pd.Timestamp) -> TradingState:
        # Build a snapshot of all required state for strategy decision-making.
        nav_history_upto_today = self.nav_history.loc[:date].copy()

        position_history_upto_today = self.shares_history.loc[:date].copy()

        return TradingState(
            position_history=position_history_upto_today,
            nav_history=nav_history_upto_today,
            current_date=date,
            current_shares=self.current_shares.copy(),
            current_nav=self.current_nav,
            trade_history=list(self.trades),
            signal_history=list(self.signal_history),
        )

    # Another debugging function
    def _reset(self):
        # Reset only histories, not prices/strategy/config — useful if you want to re-run with same object.
        self.cash = float(self.cash_start)
        self.position = pd.Series({asset:0 for asset in self.tradable_assets})
        self.current_date = self.dates[0]
        self.nav_history.clear()
        self.shares_history.clear()
        self.trades.clear()
        self.signal_history.clear()

    def _calculate_end_of_day_nav(self, date: pd.Timestamp, current_prices: pd.Series) -> float:
        # Encapsulated end-of-day bookkeeping for the portfolio state.
        # 1) Compute NAV from end-of-day cash and held dollar notionals.
        # 2) Persist NAV, shares and cash in their history objects at this date.
        self.current_nav = self.cash + self.current_shares.sum()
        self.nav_history.loc[date] = self.current_nav
        self.shares_history.loc[date, :] = self.current_shares
        self.cash_history.loc[date] = self.cash
        return self.current_nav

    def _mark_to_market_constant_notional(self, current_prices: pd.Series, previous_prices: pd.Series):
        # Revalue existing constant-dollar notionals by applying realized returns to cash.
        # Position notionals remain in dollar terms; daily PnL is transferred to cash.
        if previous_prices is None:
            return

        safe_previous = previous_prices.replace(0, np.nan)
        asset_returns = (current_prices / safe_previous - 1.0).replace([np.inf, -np.inf], np.nan).fillna(0.0)
        pnl_from_positions = (self.current_shares * asset_returns).sum()
        self.cash += pnl_from_positions

    def _calculate_delta_asset_value(self, target_asset_amt: pd.Series, target_cash_amt: float) -> pd.Series:
        assert (target_cash_amt + target_asset_amt.sum()) - self.current_nav < 1e-6, "Target portfolio is not self-financing. Please ensure that the total dollar amount of the target portfolio equals current NAV for this backtesting engine to work."
        # Encapsulated delta between desired and current dollar exposure per asset.
        # Positive values indicate buy pressure, negative values indicate sell pressure.
        return target_cash_amt - self.cash, target_asset_amt - self.current_shares

    def _calculate_commission(self, delta_asset_value: pd.Series) -> pd.Series:
        # Encapsulated commission model.
        # If 0 <= commission < 1 we treat it as a proportional rate per traded dollar.
        # Otherwise we treat commission as a flat dollar fee per non-zero traded asset.
        nonzero_trade_mask = delta_asset_value.abs() > 0
        if 0 <= self.commission < 1:
            commission_dollars = delta_asset_value.abs() * self.commission
        else:
            commission_dollars = pd.Series(0.0, index=delta_asset_value.index)
            commission_dollars.loc[nonzero_trade_mask] = float(self.commission)

        commission_total = float(commission_dollars.sum())
        self.cash -= commission_total
        return commission_total

    def _calculate_slippage(self, exec_price: pd.Series, delta_asset_value_after_commission: pd.Series) -> pd.Series:
        # Encapsulated slippage model.
        # Buys pay higher execution prices and sells receive lower execution prices.
        assert(exec_price > 0).all(), "Execution prices must be positive for slippage calculation."
        shares_wanted = delta_asset_value_after_commission / exec_price
        slippage_prices = exec_price * (1.0 + self.slippage * np.sign(delta_asset_value_after_commission))
        
        slippage_cost = (slippage_prices - exec_price) * shares_wanted
        self.cash -= slippage_cost.sum()
        return slippage_prices, slippage_cost


    def run(self, verbose=False):
        """
        Runs the backtesting engine.
        
        Parameters
        ----------
        verbose : bool, optional
        If True, returns output log each time a trade occurs, with the size of the trade and the amount traded for.
            
        Returns
        -------
        None
        """
        self.strategy_object.initialize()

        pending_target = None
        T = len(self.data) 
        previous_prices = None

        pending_cash_amount = None 
        pending_asset_amount = None

        # Starting next tick execution 
        for t in range(T):
            date = self.dates[t]
            self.current_date = date
            current_prices = self.data.loc[date, self.tradable_assets]

            # Mark-to-market PnL from existing constant-dollar notionals into cash.
            self._mark_to_market_constant_notional(current_prices, previous_prices)

            # NAV Calculation
            self._calculate_end_of_day_nav(date, current_prices)

            # Perform next tick execution (if enabled) 
            if self.execute_on_next_tick and (pending_cash_amount is not None) and (pending_asset_amount is not None):
                if verbose:
                    print(f"{date.date()}: executing pending target\n{pending_asset_amount}")

                    print(f"Current prices executed at: \n{current_prices}\n")
                self._execute_target_portfolio(pending_cash_amount, pending_asset_amount, current_prices, date)
                
                pending_asset_amount = None
                pending_cash_amount= None

            # Generate strategy signal using price history up to today
            try:
                trading_state = self._build_trading_state(date)
                # Predict desired asset amount
                pending_cash_amount, pending_asset_amount = self.strategy_object.predict(
                    self.tradable_assets,  # tradable assets
                    self.data.loc[:date],  # data
                    trading_state, # trading state
                    )

            except Exception as e:
                pending_cash_amount, pending_asset_amount = None, None
                print(f"Error in strategy.predict at index {t} date {date}: {e} - Loop continuing")
            
            self.signal_history.append(pending_asset_amount)
            
            # Immediate execution
            if not self.execute_on_next_tick:
                if verbose:
                    print(f"{date.date()}: executing pending target \n{pending_asset_amount}")
                    print(f"\nCurrent prices executed at: \n{current_prices}")
                self._execute_target_portfolio(pending_cash_amount, pending_asset_amount, current_prices, date)
                pending_asset_amount = None
                pending_cash_amount = None

            # Record end-of-day NAV, shares and cash in one encapsulated call.
            previous_prices = current_prices.copy()
            
        # Calculate backtest returns after backtest is complete.
        self.portfolio_returns = self.nav_history.pct_change().dropna()
        
        # To call other plots later, must first be sure that the backtest is done.
        self.backtest_complete=True 
        return 


    def _execute_target_portfolio(self, target_cash_amt: float, target_asset_amt: pd.Series, exec_price: pd.Series, date: pd.Timestamp):

        target_asset_amt = pd.Series(target_asset_amt, index=exec_price.index, dtype=float)
        assert len(target_asset_amt) == len(exec_price), "For some reason your execution price is not the same as the tradable assets. Try checking the backtesting code."

        note = "\n"

        if not self.allow_short:
            target_asset_amt = target_asset_amt.clip(lower=0)
            note += "Shorting not allowed, so negative asset amounts clipped to 0.\n"

        if self.current_nav <= 0:
            note = "Net Asset Value is now 0. No trades can occur.\n"
            return 

        # 1) Dollar changes needed per asset to reach target asset dollars
        delta_asset_value, delta_cash_value = self._calculate_delta_asset_value(target_asset_amt, target_cash_amt)
        
        # if tiny change, skip (reduce noise): 
        if abs(delta_asset_value.sum()) + abs(delta_cash_value) < 1e-8 * self.current_nav:
            print("Trade not executed because position rebalance was too small.")
            return

        # 2) Compute commission per stock in dollar space.
        commission_dollars = self._calculate_commission(delta_asset_value)

        # slippage: worse price depending on direction (buy => higher price, sell => lower price)
        trade_price, slippage_dollars = self._calculate_slippage(exec_price, delta_asset_value)

        # Under constant notional trading, we rebalance dollar notionals directly.
        # 
        if not self._check_position_limits(target_asset_amt):
            delta_shares_wanted = pd.Series(0.0, index=target_asset_amt.index)
            note += "Trade rejected by position limits.\n"
        else:
            delta_shares_wanted = delta_asset_value
            self.current_shares += delta_shares_wanted


        # record trade for auditing
        self.trades.append(
            Trade(
                date=date,
                shares=dict(delta_shares_wanted),
                price=dict(trade_price),
                commission=commission_dollars + slippage_dollars,
                note = note
            )
        )

        return

    def _check_position_limits(self, target_asset_amt):
        if (target_asset_amt.abs() > 2e6).any():
            return False
        return True 


from backtest.benchmarks import BuyAndHold

data = pd.DataFrame({
    "NVDA": [100, 110, 120, 130, 140],
    "AAPL": [200, 190, 195, 205, 210]
}, index=pd.date_range(start="2020-01-01", periods=5))
tickers = data.columns

buy_and_hold = BuyAndHold(1e6)
backtester_buy_and_hold = Backtester(
    data=data,
    strategy_fn=buy_and_hold,
    strategy_name="Buy and Hold",
    tradable_assets=tickers,
    cash_start=1000000,
    slippage=0.05)

# Test commission calculator