# (Trimmed snippet — use the full code run above for direct copy)

from typing import List, Dict, Optional
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
import seaborn as sns
import inspect

from backtest.data_models import Trade, TradingState
from backtest.strategy import Strategy, FunctionStrategy

sns.set_style("whitegrid")

class Backtester:
    """
    
    The core Backtesting Engine. 
    
    Parameters
    ----------
    tradable_assets : List[str]
        The assets that the strategy will make trades on. 
        
    strategy_fn : Strategy
        The function that holds the core logic of the strategy. Must be wrapped into a Strategy object before it works. 
    
    data : pd.DataFrame
        The dataset that the strategy reads to make predictions. Can include more than price data from tradable_assets. 
        The dataset inputted will have the following restrictions:
        1. The columns that consists of the price that the strategy trades on MUST be named the ticker of the asset. E.g. if trading on Adj_Close price of NVDA, change Adj_Close column name to NVDA
        2. The index of the dataset must be in the form of a datetime index. 

    allow_short : bool, optional
        Straightforward.
        
    cash_start : float, optional
        The amount of capital that the strategy starts with. 
        
    commission : float, optional
        The commission obtained by the "broker" when trades are made. (default=0.0)
        
    slippage : float, optional
        
        
    execute_on_next_tick : bool, optional
        If True, portfolio is submitted
        
    periods_per_year : int, optional
        Will be depreciated soon. 
    
    riskfree_per_period : float, optional
        Will be depreciated soon. 
    
        
    Attributes
    ----------
    tradable_assets : List[str]
        The assets that the strategy will make trades on. 

    data : pd.DataFrame
        The dataset that the strategy reads to make predictions. 

    dates : pd.DatetimeIndex
        The date index of the dataset.
    
    cash_start : float
        The cash at the start of the 
        
    current_nav : float
        
    position : pd.Series
        
    current_position : pd.Series
        
    cash : float
        
    commission : float
        
    slippage : float
        
    allow_short : bool
        Straightforward.

    execute_on_next_tick : bool
        If True, a requested portfolio is only executed on the prices of the next tick in the dataset.
    
    periods_per_year : int
        Staged for depreciation. 

    riskfree : float
        Staged for depreciation
        
    nav_history : pd.Series
        The history of Net Asset Value of the dataset. 
    
    position_history : pd.DataFrame
        The history of weights in each asset during the history of the backtest. 
        
    cash_history : pd.Series
        The amount of cash held by the strategy throughout the history of the backtest. 
        
    trades : List[Trade]
        The list of all trades sent to the 
        
    signal_history : List[Optional[pd.Series]]
        The history of signals generated by the strategy. Each entry is None or a pd.Series.
        
    strategy_object : Strategy
        The core strategy object that is tested in the engine. 
        
    strategy_name : str
        The name of the strategy that can be used in plots later. 
        
    backtest_complete : bool
        
    portfolio_returns : pd.Series
        The returns series of the strategy. 
        
    """
    def __init__(self,
                tradable_assets: List[str], 
                strategy_fn: Strategy, # The strategy function I want to test on 
                strategy_name: str, # The name of the strategy for plotting
                data: pd.DataFrame, # the data that the strategy operates on
                prices: pd.DataFrame,  # the price data that the strategy trades on (must be subset of data)
                allow_short=True,
                cash_start: float = 100_000.0,
                commission: float = 0.0,  
                slippage: float = 0.0, 
                execute_on_next_tick: bool = True,
                ):
        
        assert isinstance(strategy_fn, Strategy), "Please wrap your strategy function into a Strategy object before inputting into the backtesting engine."
        assert isinstance(data, pd.DataFrame), "Input data must be given as a pd.DataFrame indexed by date."
        assert isinstance(data.index, pd.DatetimeIndex), "Input data index must be a pd.DatetimeIndex."
        assert isinstance(prices.columns, pd.Index), "Please ensure that your prices column are a single level Index"

        assert(set(tradable_assets).issubset(set(prices.columns))), "All tradable assets must be columns in the input data. Please check your input data and tradable assets list."

        # Check the data that we need for signal generation
        self.tradable_assets = tradable_assets 
        self.data = data
        self.prices = prices

        ## need to force that the data index is in the form of dates
        self.dates = data.index
        self.current_date = self.dates[0]
        
        # Current portfolio state
        self.cash_start = cash_start
        self.current_nav = cash_start
        self.position : pd.Series = pd.Series({asset:0 for asset in self.tradable_assets})
        self.current_position: pd.Series = pd.Series({asset:0 for asset in self.tradable_assets})
        self.cash = cash_start

        # execution and model parameters
        self.commission = commission
        self.slippage = slippage
        self.allow_short = allow_short
        self.execute_on_next_tick = execute_on_next_tick

        # history
        self.nav_history: pd.Series = pd.Series(index=self.dates)
        self.position_history: pd.DataFrame = pd.DataFrame(
            0.0, 
            columns= self.tradable_assets, 
            index= self.dates)    
        assert len(self.position_history.index) == len(self.dates)
        self.cash_history: pd.Series = pd.Series(index=self.dates)
        assert list(self.position_history.columns) == list(self.tradable_assets)

        self.trades: List[Trade] = []
        self.trade_notes: Dict[pd.Timestamp, List[str]] = {}

        self.signal_history: List[Optional[pd.Series]] = []
        
        # Strategy 
        self.strategy_object = strategy_fn
        self.strategy_name = strategy_name

        # For plotting later 
        self.backtest_complete = False

        # For visualising results
        self.portfolio_returns = None

    def run(self, verbose=False):
        """
        Runs the backtesting engine.
        
        Parameters
        ----------
        verbose : bool, optional
        If True, returns output log each time a trade occurs, with the size of the trade and the amount traded for.
            
        Returns
        -------
        None
        """
        self.strategy_object.initialize()

        T = len(self.data) 
        previous_prices = None

        pending_asset_amount = None

        # Starting next tick execution 
        for t in range(T):
            date = self.dates[t]
            self.current_date = date

            current_prices = self.prices.iloc[t].dropna()
            self.tradable_assets = (current_prices.index).to_list()

            # Mark-to-market PnL from existing constant-dollar notionals into cash.
            self._mark_to_market_constant_notional(current_prices, previous_prices)

            # NAV Calculation
            self._calculate_nav(date)

            # Perform next tick execution (if enabled) 
            if self.execute_on_next_tick and pending_asset_amount is not None:
                if verbose:
                    print(f"{date.date()}: executing pending target\n{pending_asset_amount}")
                    print(f"Current prices executed at: \n{current_prices}\n")
                self._execute_target_portfolio(pending_asset_amount, current_prices, date)
                pending_asset_amount = None

            # Generate strategy signal using price history up to today
            try:
                trading_state = self._build_trading_state(t, date)
                # Predict desired asset amount
                pending_asset_amount = self.strategy_object.predict(
                    self.tradable_assets,  # tradable assets
                    self.data.iloc[: t + 1],  # data
                    trading_state,  # trading state
                )

            except Exception as e:
                pending_asset_amount = None
                print(f"Error in strategy.predict at index {t} date {date}: {e} - Loop continuing")
            
            if pending_asset_amount is None:
                self.signal_history.append(None)
            else:
                aligned = pd.Series(pending_asset_amount, dtype=float).reindex(self.tradable_assets, fill_value=0.0)
                self.signal_history.append(aligned)
            
            # Immediate execution
            if not self.execute_on_next_tick:
                if verbose:
                    print(f"{date.date()}: executing pending target \n{pending_asset_amount}")
                    print(f"\nCurrent prices executed at: \n{current_prices}")
                self._execute_target_portfolio(pending_asset_amount, current_prices, date)
                pending_asset_amount = None

            # Record end-of-day NAV, position and cash in one encapsulated call.
            previous_prices = current_prices
            
        # Calculate backtest returns after backtest is complete.
        self.portfolio_returns = self.nav_history.pct_change().dropna()
        
        # To call other plots later, must first be sure that the backtest is done.
        self.backtest_complete=True 
        return 

    # Debugging Functions 
    def _current_state(self):
        # Return a snapshot of current portfolio state (useful for debugging).
        return {
            "cash": self.cash,
            # To dict method converts pandas Series to dictionary for easier view 
            "nav": self.cash + (self.current_position).sum()
        }

    def _build_trading_state(self, end_idx: int, date: pd.Timestamp) -> TradingState:
        # Build a snapshot of all required state for strategy decision-making.
        slice_end = end_idx + 1
        nav_history_upto_today = self.nav_history.iloc[:slice_end].copy(deep=False)
        position_history_upto_today = self.position_history.iloc[:slice_end].copy(deep=False)

        return TradingState(
            position_history=position_history_upto_today,
            nav_history=nav_history_upto_today,
            current_date=date,
            current_position=self.current_position.copy(deep=False),
            current_nav=self.current_nav,
            trade_history=list(self.trades),
            signal_history=list(self.signal_history),
        )

    # Another debugging function
    def _reset(self):
        # Reset only histories, not prices/strategy/config — useful if you want to re-run with same object.
        self.cash = float(self.cash_start)
        self.current_position = pd.Series({asset:0 for asset in self.tradable_assets})
        self.current_date = self.dates[0]
        self.nav_history.clear()
        self.position_history.clear()
        self.trades.clear()
        self.signal_history.clear()

    def _calculate_nav(self, date: pd.Timestamp) -> float:
        # Encapsulated end-of-day bookkeeping for the portfolio state.
        # 1) Compute NAV from end-of-day cash and held dollar notionals.
        # 2) Persist NAV, position and cash in their history objects at this date.
        self.current_nav = self.cash + self.current_position.sum()
        self.nav_history.loc[date] = self.current_nav
        self.position_history.loc[date, :] = self.current_position
        self.cash_history.loc[date] = self.cash
        return self.current_nav
        
    def _mark_to_market_constant_notional(self, current_prices: pd.Series, previous_prices: pd.Series):
        # First tick has no previous prices — nothing to mark.
        if previous_prices is None:
            return

        # Only mark assets present in both snapshots AND currently held.
        # Delisted assets (in current_position but not in current_prices) are excluded
        # here; their notional will be recycled to cash in _execute_target_portfolio.
        active_assets = self.current_position[self.current_position != 0].index
        common_assets = current_prices.index.intersection(previous_prices.index).intersection(active_assets)

        if len(common_assets) == 0:
            return

        safe_previous = previous_prices[common_assets].replace(0, np.nan)
        asset_returns = (
            (current_prices[common_assets] / safe_previous - 1.0)
            .replace([np.inf, -np.inf], np.nan)
            .fillna(0.0)
        )
        pnl_from_positions = (self.current_position[common_assets] * asset_returns).sum()
        self.cash += pnl_from_positions

        return 

    def _calculate_delta_asset_value(self, target_asset_amt: pd.Series) -> pd.Series:
        # Encapsulated delta between desired and current dollar exposure per asset.
        # Positive values indicate buy pressure, negative values indicate sell pressure.
        return target_asset_amt - self.current_position

    def _calculate_commission(self, delta_asset_value: pd.Series) -> pd.Series:
        # Encapsulated commission model.
        # If 0 <= commission < 1 we treat it as a proportional rate per traded dollar.
        # Otherwise we treat commission as a flat dollar fee per non-zero traded asset.
        nonzero_trade_mask = delta_asset_value.abs() > 0
        if 0 <= self.commission < 1:
            commission_dollars = delta_asset_value.abs() * self.commission
        else:
            commission_dollars = pd.Series(0.0, index=delta_asset_value.index)
            commission_dollars.loc[nonzero_trade_mask] = float(self.commission)

        commission_total = float(commission_dollars.sum())
        self.cash -= commission_total
        return commission_total

    def _calculate_slippage(self, exec_price: pd.Series, delta_asset_value_after_commission: pd.Series) -> pd.Series:
        # Encapsulated slippage model.
        # Buys pay higher execution prices and sells receive lower execution prices.
        assert(exec_price.index == delta_asset_value_after_commission.index).all(), "Execution price and asset value change must have the same index for slippage calculation."
        assert(exec_price > 0).all(), "Execution prices must be positive for slippage calculation."

        
        position_wanted = delta_asset_value_after_commission / exec_price
        slippage_prices = exec_price * (1.0 + self.slippage * np.sign(delta_asset_value_after_commission))
        
        slippage_cost = (slippage_prices - exec_price) * position_wanted
        assert(isinstance(slippage_cost, pd.Series)), "Slippage cost should be a pd.Series with the same index as exec_price."
        self.cash -= slippage_cost.sum()
        return slippage_prices, slippage_cost

    def _execute_target_portfolio(self, target_asset_amt: pd.Series, exec_price: pd.Series, date: pd.Timestamp):
        # Add trading notes
        self.trade_notes[date] = []
        # ------------------------------------------------------------------ #
        # Step 1: Forced liquidation of delisted assets (NAV-preserving).    #
        # Any asset currently held whose price is absent from exec_price is  #
        # now untradable.  Its dollar notional is recycled to cash at book    #
        # value so NAV (= cash + current_position.sum()) is unchanged.         #
        # ------------------------------------------------------------------ #
        delisted_assets = self.current_position.index.difference(exec_price.index)
        if len(delisted_assets) > 0:
            self.cash += self.current_position[delisted_assets].sum()
            self.current_position = self.current_position.drop(index=delisted_assets)

        # ------------------------------------------------------------------ #
        # Step 2: Align current_position to the live tradable universe.        #
        # Assets that appear in exec_price for the first time start at 0.    #
        # ------------------------------------------------------------------ #
        if not self.current_position.index.equals(exec_price.index):
            self.current_position = self.current_position.reindex(exec_price.index, fill_value=0.0)

        # ------------------------------------------------------------------ #
        # Step 3: Align the strategy's target to the live tradable universe. #
        # Targets for delisted assets are silently dropped; any asset with   #
        # no explicit target defaults to 0 (close the position).             #
        # ------------------------------------------------------------------ #
        target_asset_amt = pd.Series(target_asset_amt, dtype=float).reindex(exec_price.index, fill_value=0.0)

        if not self.allow_short:
            target_asset_amt = target_asset_amt.clip(lower=0)
            self.trade_notes[date].append("Asset Weights clipped to 0 because of no shorting allowed")

        # 1) Dollar changes needed per asset to reach target asset dollars
        delta_asset_value = self._calculate_delta_asset_value(target_asset_amt)

        # if tiny change, skip (reduce noise):
        if abs(delta_asset_value).sum() < 1e-8 * self.current_nav:
            self.trade_notes[date].append("Position rebalance too small - trade not executed")
            return

        # 2) Compute commission per stock in dollar space.
        commission_dollars = self._calculate_commission(delta_asset_value)

        # 3) Slippage: worse price depending on direction
        trade_price, slippage_dollars = self._calculate_slippage(exec_price, delta_asset_value)

        # Under constant notional trading, we rebalance dollar notionals directly.
        if not self._check_position_limits(target_asset_amt):
            delta_position_wanted = pd.Series(0.0, index=target_asset_amt.index)
            self.trade_notes[date].append(f"Trade rejected by position limits at {date}.")
        else:
            delta_position_wanted = delta_asset_value
            self.current_position += delta_position_wanted
            self.cash -= delta_position_wanted.sum()

        # Record trade for auditing.
        trade = Trade(date, delta_position_wanted, trade_price, commission_dollars, float(slippage_dollars.sum()))
        self.trades.append(trade)

        return

    def _check_position_limits(self, target_asset_amt):
        if (target_asset_amt.abs() > 2e6).any():
            return False
        return True 
